name: flutter_sandbox
description: A sandbox to place all Flutter learnings.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  animated_text_kit: ^2.1.0
  flutter_bloc: ^4.0.0
  
dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans-Italic.ttf
          style: italic 
        - asset: fonts/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600
